apiVersion: v2
name: ace
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: hello
  repository: file://../hello
  version: 0.1.0
  condition: one.enabled
  alias: one
- name: hello
  repository: file://../hello
  version: 0.1.0
  condition: two.enabled
  alias: two
